### PR TITLE
add link cliche plugin

### PR DESCRIPTION
**Pull request by dunckr**
I made [this](https://github.com/dunckr/retext-cliches) plugin for checking for cliches.

Any thoughts about it would be cool!

Might want to hold off merging in until I can figure out how to get my travis test to pass on every version node though.

Cheers

### CODE REVIEW

**Comment by dunckr** [comment]
I fixed the issue with forked ```no-cliches``` library on node ```v0.10``` and the tests now pass.

**Comment by wooorm** [comment]
Looks good, and very useful! Nice work; merging!

**Comment by wooorm** [comment]
Whoops, forgot to close this from 48dc4d9c910f055bd016d91e6fff8bb80a57439a.

**Comment by dunckr** [comment]
Cool ty!

**Comment by mugendi** [comment]
This is extremely useful. Thanks all.

**Comment by wooorm** [comment]
:+1:

**Pull request closed without merging**
